# build:
#   stage: build
#   tags: [windows, desktop]
#   script:
#     - ./build-installer.ps1
#   artifacts:
#     paths:
#       - ./installer/Output/dep-installer.exe
#     expire_in: never

release:
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - go install gitlab.com/gitlab-org/release-cli/cmd/release-cli@latest
    - echo "Create release"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
  artifacts:
    paths:
      - release/installer.exe